data_dir: "../data"
metadata_path: "../data/deeplesion_metadata.csv"

environment:
  render: true
  max_steps: 100                        # Max steps the agent can take before the episode ends
  bbox_move_step_factor: 0.1
  bbox_resize_factor: 0.1
  initial_bbox_width: 50
  initial_bbox_height: 50
  bbox_pixel_margin: 10                 # Number of margin pixels around the bounding box (in every direction)
  bbox_min_length: 10                   # Minimal bounding box width/height
  bbox_max_length: 64                   # Maximal bounding box width/height
  bbox_max_aspect_ratio: 3.0            # Maximal aspect ratio of the bounding box
  bbox_randomize: true
  bbox_position_shift_range: 50
  bbox_size_shift_range: 10
  n_previous_actions: 10                # Number of previous actions stored in the observation
  iou_threshold: 0.7

  reward:
    alpha_1: 10.0                       # Weight of the IoU reward component
    alpha_2: 2.0                        # Weight of the delta IoU reward component
    beta: 2.0                           # Weight of the delta distance reward component 
    step_penalty: -1.0
    iou_final_reward: 20.0              # Additional, big reward on finishing step, when IoU >= threshold

agent:
  learning_rate: 0.0001
  gamma: 0.99                           # discount factor
  epsilon_start: 1.0
  epsilon_end: 0.1
  epsilon_decay: 100
  replay_buffer_size: 10000
  target_update_steps: 100              # Number of steps after which the target network is updated
  batch_size: 32 # 64
  fixed_patch_length: 64                # Fixed length (widht/height) of the patch (input width/height of the CNN) 

train:
  train_episodes: 1000
  log_interval: 10                      # print/log progress every X episodes
  save_interval: 50                     # chackpoint model every X episodes
  output_dir: "../runs/localizer/logs"  # path for saving logs, checkpoints etc.

test:
  test_episodes: 20
  model_checkpoint: "../runs/localizer/checkpoints/agent_lastest.pt"

logging:
  level: INFO
  format: "(%(asctime)s) %(name)s [%(levelname)s]: %(message)s"
  datefmt: "%Y-%m-%d %H:%M:%S"