environment:
  dataset_path: ""
  metadata_file: "../data/deeplesion_metadata.csv"

  max_steps: 100 # Max steps the agent can take before the episode ends
  bbox_move_step: 5
  initial_bbox_width: 20
  initial_bbox_height: 20
  bbox_crop_width: 64
  bbox_crop_height: 64
  image_crop_width: 512 # Only for images of size different than 512x512
  image_crop_height: 512 # Only for images of size different than 512x512

agent:
  learning_rate: 0.0001
  gamma: 0.99 # discount factor
  epsilon_start: 1.0
  epsilon_end: 0.1
  epsilon_decay: 10000
  replay_buffer_size: 100000
  batch_size: 64

train:
  train_episodes: 1000
  log_interval: 10                      # print/log progress every X episodes
  save_interval: 50                     # chackpoint model every X episodes
  output_dir: "../runs/localizer/logs"  # path for saving logs, checkpoints etc.

test:
  test_episodes: 20
  model_checkpoint: "../runs/localizer/checkpoints/agent_lastest.pt"

logging:
  level: INFO
  format: "(%(asctime)s) %(name)s [%(levelname)s]: %(message)s"
  datefmt: "%Y-%m-%d %H:%M:%S"